/* 
    * SALESDB_CODE.sql - Lab 8 *
    Name: Billy Conard 
    Date: 05/28/26
*/

SET SERVEROUTPUT ON FORMAT WRAPPED;
SET VERIFY OFF;

-- Test FUNCTION GET_ORDERTOTAL 
SELECT OrderID,
       SALESDB_CODE.GET_ORDERTOTAL(OrderID) AS OrderTotal
FROM   
(
    SELECT DISTINCT OrderID
    FROM   ORDERS 
UNION
    SELECT 99999
    FROM DUAL
);

-- Test FUNCTION GET_PROFITABILITY
SELECT EmpID,
       SALESDB_CODE.GET_PROFITABILITY(EmpID) AS ProfitVal
FROM 
(
    SELECT DISTINCT EmpID
    FROM   SALESPERSONS
UNION
    SELECT -9999
    FROM   DUAL
);

-- Test FUNCTION GET_NEWDETAIL
SELECT OrderID,
       SALESDB_CODE.GET_NEWDETAIL(OrderID)
FROM 
(
    SELECT DISTINCT OrderID
    FROM ORDERITEMS
UNION
    SELECT -000000
    FROM DUAL
);

-- Test PROCEDURE with various values 
-- PARAMETER_SPECS(OrderID, PartID, Qty) 
BEGIN
    
    SALESDB_CODE.ADDLINEITEM(6099, 1009, 1);      -- Clean addition 
    SALESDB_CODE.ADDLINEITEM(6128, 1006, 150);    --Bad Qty - should raise an error
    
END;

